### ISSUE TITLE
Last Recall : Client crashes when hovering recall orb on World Map

### ISSUE THREAD

**Issue by tylerthardy** [dekvall/runelite-external-plugins#90]
```
2023-11-21 18:37:26 EST [Client] ERROR client-patch - Client error
java.lang.AssertionError: null
	at net.runelite.client.ui.overlay.worldmap.WorldMapOverlay.render(WorldMapOverlay.java:225)
	at net.runelite.client.ui.overlay.OverlayRenderer.safeRender(OverlayRenderer.java:734)
	at net.runelite.client.ui.overlay.OverlayRenderer.renderOverlays(OverlayRenderer.java:328)
	at net.runelite.client.ui.overlay.OverlayRenderer.renderAfterInterface(OverlayRenderer.java:242)
	at net.runelite.client.callback.Hooks.drawInterface(Hooks.java:548)
	at client.mz(client.java:10581)
	at bz.lk(bz.java:11097)
	at ag.ln(ag.java:10683)
	at bz.lk(bz.java:10823)
	at bz.lk(bz.java:10819)
	at bz.lk(bz.java:10819)
	at bz.lk(bz.java:10819)
	at ag.ln(ag.java:10683)
	at client.mf(client.java:4598)
	at client.bw(client.java:1191)
	at bm.ad(bm.java:424)
	at bm.bu(bm.java)
	at bm.run(bm.java:48840)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by dekvall** [comment]
Fixed in #91
